GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Maria Mars",
  "number": "778-887-7788"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Maria Test",
  "number": "123"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "test",
  "number": ""
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Arto Hellas",
  "number": "778-887-7788"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
   
}
###
DELETE DELETE http://localhost:3001/api/persons/60ee5cadafd2c6af6220d8ca HTTP/1.1